### ISSUE TITLE
Pass data between controllers

### ISSUE THREAD

**Issue by pardnoj** [mluton/EmbeddedSwapping#9]
I am trying to pass data from my view controller to child view controllers via container controller. How can I do that?

**Comment by Isuru-Nanayakkara** [comment]
@mluton Just wanted to say thanks. This helped me a ton! :+1:

**Comment by Isuru-Nanayakkara** [comment]
Just wanted to say thanks. This helped me a ton! :+1:

**Comment by mluton** [comment]
I appreciate the positive feedback. Glad it helped!
